name: Set Package Visibility

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  set-visibility:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write

    steps:
      - name: Set package visibility to public
        run: |
          PACKAGE_NAME="magicfy-web"
          OWNER="${{ github.repository_owner }}"

          echo "Setting visibility for package: $PACKAGE_NAME"

          # Set package visibility to public
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/user/packages/container/$PACKAGE_NAME" \
            -d '{"visibility":"public"}'

          echo "Package visibility updated successfully"
